version: '3'

services:
  api:
    container_name: spk_api
    restart: always
    image: bsfranca2/spk-api
    environment:
      - NODE_ENV=production
    expose:
      - 3000
    ports:
      - 3000:3000
    env_file:
      - /etc/environment
