version: '3'

services:
  postgres:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: speakupify
    ports:
      - 5432:5432
    networks:
      - main

volumes:
  postgres-data:

networks: 
  main:
